const data = {
    products:[
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Product',
        },
        {
            _id: '2',
            name: 'Adidas Slim Shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 110,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 11,
            description: 'High Quality Product',
        },{
            _id: '3',
            name: 'Reebok Slim Shirt',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: 100,
            brand: 'Reebok',
            rating: 3.5,
            numReviews: 12,
            description: 'High Quality Product',
        },{
            _id: '4',
            name: 'Anta Slim Shirt',
            category: 'Shirts',
            image: '/images/p4.jpg',
            price: 90,
            brand: 'Anta',
            rating: 3.1,
            numReviews: 13,
            description: 'High Quality Product',
        },{
            _id: '5',
            name: 'New Balance Slim Shirt',
            category: 'Shirts',
            image: '/images/p5.jpg',
            price: 80,
            brand: 'New Balance',
            rating: 4.9,
            numReviews: 14,
            description: 'High Quality Product',
        },{
            _id: '6',
            name: 'Converse Slim Shirt',
            category: 'Shirts',
            image: '/images/p6.jpg',
            price: 70,
            brand: 'Converse',
            rating: 4.2,
            numReviews: 15,
            description: 'High Quality Product',
        },
    ],
};

export default data;